version: '3.7'

services:

  # REF: https://hub.docker.com/r/netdata/netdata
  netdata:
    image: netdata/netdata:v1.13.0-armhf
    # https://docs.netdata.cloud/daemon/#command-line-options and variables "${blah}" from .env file
    command: -W set backend destination "${destination}" -W set registry 'registry to announce' "${registry}"
    hostname: netdata
    environment:
      - PGID=996
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    ports:
      # netdata unencrypted UDP 19999
      - mode: host
        target: 19999
        published: 19999
        protocol: tcp
    networks:
      - netdata-stack-net1
    volumes:
      - type: bind
        source: /opt/netdata/etc/netdata/netdata.conf
        target: /etc/netdata/netdata.conf
      - type: bind
        source: /proc
        target: /host/proc
        read_only: true
      - type: bind
        source: /sys
        target: /host/sys
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      labels:
        local.description: "netdata"
      restart_policy:
        condition: always 

networks:
  netdata-stack-net1:
